### ISSUE TITLE
トロフィー: 単調増加する指標を列挙

### ISSUE THREAD

**Issue by KATO-Hiro** [KATO-Hiro/AtCoderTrophies#36]
- [ ] #480
- [ ] Ratedコンテストの参加回数
  - [ ] #503
  - [ ] #504
- [ ] AC数
  - [x] 全体 solved by #147 
  - [x] 言語別、AtCoder ProblemsのLang ownerで1000AC以上されている言語を優先的に
    - [x] #307
    - [x] #306
    - [x] #305
    - [x] #160 
    - [x] #161
    - [x] #162
    - [x] #298
    - [x] #299
    - [x] #163
    - [x] #304
    - [x] #176
    - [x] #194
    - [x] #303
    - [x] #164
    - [x] #204
    - [x] #302
    - [x] #193
    - [x] #205
    - [x] #300
    - [x] #191
    - [x] #301
    - [x] #192
    - [x] #165
    - [x] #166
    - [x] #167
    - [x] #168
    - [x] #206
    - [x] #353
    - [x] #354
    - [x] #355
    - [x] #356
    - [x] #357
    - [x] #358
    - [x] #359
    - [x] #360
    - [x] #361
    - [x] #362
    - [x] #387
    - [x] #388
    - [x] #389
    - [x] #390
    - [x] #391
    - [x] #392
    - [x] #393
    - [x] #394
    - [x] #395
    - [x] #396
    - [x] #397
    - [x] #398
    - [x] #399
    - [x] #400
    - [x] #401
    - [x] #402
    - [x] #403
    - [x] #404
    - [x] #405
    - [x] #406
    - [x] #425
    - [x] #426
    - [x] #473
    - [x] #474
  - [ ] 1日最大
  - [ ] コンテストカテゴリ別
    - [ ] #505
    - [ ] #506
    - [ ] #507
    - [ ] ABC-like
    - [ ] ARC-like
    - [ ] AGC-like
    - [ ] PAST
    - [ ] AHC
    - [ ] Marathon
    - [ ] Others 
- [ ] Streak
  - [ ] 現在: ProblemsのAPIから取得するのは難しそう
  - [x] 最長  solved by #180 
- [x] Rated Point Sum solved by #152 
- [ ] #339
- [ ] 隠し要素
  - [x] 全てのランクがS以上 solved by #180 
  - [ ] 全てのトロフィーを獲得 
- [ ] First AC: ProblemsのAPIから取得するのは難しそう
- [ ] Fastest AC: ProblemsのAPIから取得するのは難しそう
- [ ] Shortest AC: ProblemsのAPIから取得するのは難しそう
- [ ] TEE
- [ ] 典型90問
  - [ ] 得点
  - [ ] 問題数
- [ ] #321
- [ ] Trophies へのアクセス回数
- [ ] 最初のRatedコンテストに参加してからの経過年数
